# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.

name: "Ruby on Rails CI"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]  
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: test
          POSTGRES_USER: ${{ vars.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ vars.DATABASE_PASSWORD }}
    env:
      RAILS_ENV: test
      DATABASE_URL: ${{ vars.DATABASE_URL }}
      DATABASE_HOST: ${{ vars.DATABASE_HOST }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Set up database schema
      #  run: bin/rails db:schema:load
        run: bin/rails db:load
      # Add or replace test runners here
      - name: Run tests
        run: bin/rake

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      # Add or replace any other lints here
      #- name: Security audit dependencies
      #  run: bin/bundler-audit --update
      #- name: Security audit application code
      #  run: bin/brakeman -q -w2
      #- name: Lint Ruby files
      #  run: bin/rubocop --parallel
      
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Setup environment variables
      run: |
        echo "DATABASE_URL=$DATABASE_URL" >> .env
        echo "RAILS_MASTER_KEY=$RAILS_MASTER_KEY" >> .env

    - name: Run tests
      env:
        RAILS_ENV: test
      run: |
        rails db:create
        rails db:migrate
        rails test

    #- name: Deploy to production
    #  if: ${{ github.ref == 'refs/heads/main' }}
    #  run: |
    #    ssh user@yourserver.com << EOF
    #      cd /path/to/your/rails/app
    #      git pull
    #      bundle install --jobs 4 --retry 3
    #      rails db:migrate
    #      exit
    #    EOF
